### ISSUE TITLE
Pass a <Component/> into `describe`.

### ISSUE THREAD

**Issue by philcockfield** [philcockfield/ui-harness#23]
As well as a String option, allow an actual `<Component>` to be used as the description of a `describe` statement, and then auto-load that component upon selection of the suite.

---
See also: https://github.com/philcockfield/ui-harness/issues/24

**Comment by philcockfield** [comment]
## Examples

Without props (simple)

```js
describe(<MyComponent/>, function() {
  ...
});
```

With props:

```js
describe(<MyComponent color="red" />, function() {
  ...
});
```

**Comment by frederickfogerty** [comment]
There's quite a bit of complexity around the name of a component, see https://github.com/philcockfield/js-bdd/blob/master/src/suite.js#L166 and https://github.com/philcockfield/js-bdd/blob/master/src/api.js#L143

If the '::' stuff isn't needed then we could do this, otherwise I'm in favour of closing.

**Comment by philcockfield** [comment]
Closing.  Not needed in practice.
