### ISSUE TITLE
Support node < 5.5

### ISSUE THREAD

**Issue by frederickfogerty** [philcockfield/ui-harness#26]
Just curious what this hard dependency is for - it's going to turn a lot of people away, as they can't be bothered upgrading to 5.5, or they could have no choice but to use the LTS or *gasp* `0.12`.

**Comment by philcockfield** [comment]
What's your suggested min?  

I'd like to not go lower than `5.x` because that's when the new flat `node_modules` scheme came in with (with NPM ver 3+ I think).

Rationale: The UIHarness relies on that so that the referencing (parent) module has all the common module-references it needs (React, Babel etc).  The design goal of that was to be able to have very clean simple `package.json` declarations, with just the actual modules that were unique to the UI components, and not loaded up with essentially boilerplate (which, with Babel-6 is not an insignificant amount of noise).

I went up to 5.5 when something weird happened with Harrison installing it (I think on 5.2).  I just moved it up to 5.5 without spending a lot of time investigating, so I don't imagine there would be any real problem pulling this back to some lower version (with just a bit of debugging).

**Comment by frederickfogerty** [comment]
I would suggest v4 or LTS as min. 

npm v3 can definitely be used with v4 (I've been using it since 0.12), it just became default in v5. `npm i -g npm@3` will install it for earlier versions. 

To be honest I'm not sure I completely understand the UI Harness architecture, but isn't that sort of arch also valid in npm v2? Node has always traversed up the tree to try find dependencies - npm v3 didn't change that. In fact, I don't see why this wouldn't work on 0.12 (with the right babel transforms of course)

I'm pretty sure I'm missing something here so please call me out on anything I'm incorrect about.

**Comment by philcockfield** [comment]
Yeah - sounds good

**Comment by frederickfogerty** [comment]
Closing as 6 is now stable... should be good enough for most people
